services:
  kali-linux:
    build: .
    container_name: ${CONTAINER_NAME:-kali-linux-container}
    hostname: ${HOSTNAME:-kali-linux}
    tty: true
    stdin_open: true
    privileged: true
    volumes:
      - kali-data:/root
      - ./shared:/shared
    networks:
      - kali-network
    ports:
      - "${HTTP_PORT:-80}:80" # HTTP port
      - "${HTTPS_PORT:-443}:443" # HTTPS port
      - "${ALT_HTTP_PORT:-8080}:8080" # Alternative HTTP port
      - "${DOCKER_ADB_PORT:-6037}:5037" # Custom ADB server port for container
      - "6554-6585:5554-5585" # Custom emulator ports range for container
    environment:
      - TERM=xterm-256color
    restart: unless-stopped

volumes:
  kali-data:
    driver: local

networks:
  kali-network:
    driver: bridge
